{"0": {"author": "JEEVARATHINAM", "date": "1645725942955", "content": "Hi,\ni was trying to execute the in code in github\nhttps://github.com/sophchoe/Binary_Classification_Pennylane_Keras/blob/main/fraud_detection_Pennylane_Keras.ipynb 14\nbut i was getting error in  Quantum Circuit part of this code\n# select a device \n\ndev = qml.device(\"strawberryfields.fock\", wires=num_modes, cutoff_dim=num_basis)\n\nhere the error comes like\n\n---------------------------------------------------------------------------\nDeviceError                               Traceback (most recent call last)\n<ipython-input-19-4b62c45398d1> in <module>()\n      3 \n      4 # select a devide\n----> 5 dev = qml.device(\"strawberryfields.fock\", wires=num_modes, cutoff_dim=num_basis)\n      6 \n      7 @qml.qnode(dev, interface=\"tf\")\n\n/usr/local/lib/python3.7/dist-packages/pennylane/__init__.py in device(name, *args, **kwargs)\n    303         return dev\n    304 \n--> 305     raise DeviceError(\"Device does not exist. Make sure the required plugin is installed.\")\n    306 \n    307 \n\nDeviceError: Device does not exist. Make sure the required plugin is installed.\n\npls give me your inputs on this\ni will also attach my google colab link\nhttps://colab.research.google.com/drive/1JPqLRMYFX54IIpEt2aI67-E4SyP1xxRv?usp=sharing 18\nthanks!\nlooking forward to your support", "link": "https://discuss.pennylane.ai//t/device-does-not-exist-make-sure-the-required-plugin-is-installed/1698/1"}, "1": {"author": "CatalinaAlbornoz", "date": "1645735475789", "content": "Hi @JEEVARATHINAM,\nYou need to have installed the PennyLane-SF plugin 89.\nYou can install it using pip install PennyLane-SF.\nI hope this helps!1", "link": "https://discuss.pennylane.ai//t/device-does-not-exist-make-sure-the-required-plugin-is-installed/1698/2"}, "2": {"author": "JEEVARATHINAM", "date": "1645750168426", "content": "Now im getting error while runing the model training part\nwhile executing the below code\nopt = keras.optimizers.Adam(learning_rate=0.01)\n\nmodel.compile(opt, loss = 'MSE', metrics = ['accuracy'])\n\nhistory = model.fit(X_train, \n\n                    y_train,\n\n                    epochs = 40,\n\n                    batch_size = 190,\n\n                    shuffle = True,\n\n                    validation_data=(X_test, y_test))\n\n\nim getting error like:\n\n\n\nEpoch 1/40\n---------------------------------------------------------------------------\nInvalidArgumentError                      Traceback (most recent call last)\n<ipython-input-11-beac6fcaf23e> in <module>()\n      8                     batch_size = 190,\n      9                     shuffle = True,\n---> 10                     validation_data=(X_test, y_test))\n\n\n1 frames\n/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)\n   7184 def raise_from_not_ok_status(e, name):\n   7185   e.message += (\" name: \" + name if name is not None else \"\")\n-> 7186   raise core._status_to_exception(e) from None  # pylint: disable=protected-access\n   7187 \n   7188 \n\nInvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:Mul]\n\nlooking forward to your support\nFor reference look the same colab which i had mentioned in the first post of this topic\nThanks!\nTry to run this code in your lap\u2026using the GitHub\u2026", "link": "https://discuss.pennylane.ai//t/device-does-not-exist-make-sure-the-required-plugin-is-installed/1698/3"}, "3": {"author": "CatalinaAlbornoz", "date": "1645813035732", "content": "Hi @JEEVARATHINAM from what I see in the error, your data is a different type from what the code says it is. Notice how in the code you\u2019re specifying that your data is of type \u201cfloat32\u201d but apparently it\u2019s not. I\u2019d try converting your data or changing the type specified in the code.\nAlso, try to run the demo exactly as it is with the dataset provided. If you run into issues in that case then the problem might be different.\nI hope this helps!", "link": "https://discuss.pennylane.ai//t/device-does-not-exist-make-sure-the-required-plugin-is-installed/1698/4"}, "4": {"author": "JEEVARATHINAM", "date": "1645823574754", "content": "hi,\nJust now I again tried running the code.\ni didnt do anychange with data i m just executing with same csv file which is from zip folder.\nStill I m getting errors\nso pls help me with that\nhere in am attaching the csv file link\n\n\ndrive.google.com\n\n\n\nccfraud_10_features_1968.csv 1\nGoogle Drive file.\n\n\n\n\n\n\nyou can download and execute the code in your lap.\nlooking forward to your suggestion\nPls refer to the same notebook in the first post of this topic.\nFeel free to edit", "link": "https://discuss.pennylane.ai//t/device-does-not-exist-make-sure-the-required-plugin-is-installed/1698/5"}, "5": {"author": "CatalinaAlbornoz", "date": "1645827000861", "content": "Hi @JEEVARATHINAM, I\u2019m able to reproduce your error. It\u2019s strange because this demo run perfectly when it was submitted. You should create a new virtual environment with the same versions as specified on the top of the notebook. This should make the demo work again.", "link": "https://discuss.pennylane.ai//t/device-does-not-exist-make-sure-the-required-plugin-is-installed/1698/6"}, "6": {"author": "josh", "date": "1645977840496", "content": "Hi @JEEVARATHINAM; if you install an external plugin device on Colab, you will need to restart the runtime ( Runtime \u2192 Restart Runtime ) before the newly installed PennyLane devices are available.\nLet me know if that helps!", "link": "https://discuss.pennylane.ai//t/device-does-not-exist-make-sure-the-required-plugin-is-installed/1698/7"}, "7": {"author": "JEEVARATHINAM", "date": "1645983839040", "content": "Hi,\nThank you for your help.\nMany times I had restarted the runtime both in colab as well as in databricks. But the code is not working\nIt will be very helpful if we connect through Google meet. So that we can rectify this error in my environment.\nI m ready to share the invite as per your schedule.\nLooking forward to your support.\nKindly help me. Forsure I will help many others\u2026who are facing this same issue\nThanks!", "link": "https://discuss.pennylane.ai//t/device-does-not-exist-make-sure-the-required-plugin-is-installed/1698/8"}, "8": {"author": "CatalinaAlbornoz", "date": "1646104254903", "content": "Hi @JEEVARATHINAM, unfortunately we cannot connect through a google meet. I will keep looking onto how this problem can be fixed and if you want we can meet at the PennyLane community calls which we hold on Thursdays at 11am ET on the Unitary Fund Discord (in the community-call voice channel).", "link": "https://discuss.pennylane.ai//t/device-does-not-exist-make-sure-the-required-plugin-is-installed/1698/9"}, "9": {"author": "JEEVARATHINAM", "date": "1646133515706", "content": "Hi,\nThank you so much for your guidance.\nAtlast I have run my model in databricks community edition.\nBut I am struggling to save the model.\nIt shows me error while saving the model\nCan you guide me how to save this model in a proper way.\nThanks!1 Reply", "link": "https://discuss.pennylane.ai//t/device-does-not-exist-make-sure-the-required-plugin-is-installed/1698/10"}, "10": {"author": "CatalinaAlbornoz", "date": "1646261676875", "content": "Hi @JEEVARATHINAM, can you please share your code and the error you\u2019re getting when saving the model? If it\u2019s a databricks issue then it\u2019s best to ask them directly. If it\u2019s a PennyLane issue then we can help.2 Replies", "link": "https://discuss.pennylane.ai//t/device-does-not-exist-make-sure-the-required-plugin-is-installed/1698/11"}, "11": {"author": "sy1234", "date": "1650969680309", "content": "hello! have you solved  the problem yet?\ni had the same problem", "link": "https://discuss.pennylane.ai//t/device-does-not-exist-make-sure-the-required-plugin-is-installed/1698/12"}, "12": {"author": "sy1234", "date": "1650974237581", "content": "\nimage1706\u00d7930 125 KB\n", "link": "https://discuss.pennylane.ai//t/device-does-not-exist-make-sure-the-required-plugin-is-installed/1698/13"}, "13": {"author": "sy1234", "date": "1650974307581", "content": "what should I do?\nthanks very much!", "link": "https://discuss.pennylane.ai//t/device-does-not-exist-make-sure-the-required-plugin-is-installed/1698/14"}, "14": {"author": "CatalinaAlbornoz", "date": "1651011342059", "content": "Hi @sy1234,\nThe current demo has a lot of dtype assignments to float32 and int32. Your computer probably requires you to change this to float64 and int64.\nPlease let me know if these changes solve your problem!", "link": "https://discuss.pennylane.ai//t/device-does-not-exist-make-sure-the-required-plugin-is-installed/1698/15"}, "15": {"author": "sy1234", "date": "1650974237581", "content": "\nimage1706\u00d7930 125 KB\n", "link": "https://discuss.pennylane.ai//t/device-does-not-exist-make-sure-the-required-plugin-is-installed/1698/16"}}