{"0": {"author": "oscar-wallis", "date": "1681751381153", "content": "Hi,\nI recently installed the pennylane orquestra plugin as I\u2019m trying to run some hybrid neural nets on IBM hardware but I\u2019m getting file not found errors when trying to use any orquestra backends. I\u2019m running on Python 3.9.13 through Anaconda and have pennylane 0.29.1 and pennylane-orquestra 0.28.0 installed (shown in conda list), and I can run fine on pennylane backends, just having issues on orquestra. I\u2019m not experienced in python environments so I imagine this may not be an orquestra issue but I haven\u2019t had it on any other packages I\u2019ve installed and used thus far. This is the error I\u2019m getting:\nError\nc:\\Users\\oscar\\Documents\\Masters ML\\Neural Net>C:/Users/oscar/anaconda3/python.exe \u201cc:/Users/oscar/Documents/Masters ML/Neural Net/OrquestraTest.py\u201d\nTraceback (most recent call last):\nFile \u201cc:\\Users\\oscar\\Documents\\Masters ML\\Neural Net\\OrquestraTest.py\u201d, line 13, in \nprint(circuit(0,0,1))\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane\\qnode.py\u201d, line 889, in call\nres = qml.execute(\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane\\interfaces\\execution.py\u201d, line 729, in execute\nres = _execute(\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane\\interfaces\\autograd.py\u201d, line 81, in execute\nreturn _execute(\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\autograd\\tracer.py\u201d, line 48, in f_wrapped\nreturn f_raw(*args, **kwargs)\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane\\interfaces\\autograd.py\u201d, line 125, in _execute\nres, jacs = execute_fn(tapes, **gradient_kwargs)\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane\\interfaces\\execution.py\u201d, line 205, in wrapper\nres = fn(execution_tapes.values(), **kwargs)\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane\\interfaces\\execution.py\u201d, line 131, in fn\nreturn original_fn(tapes, **kwargs)\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\contextlib.py\u201d, line 79, in inner\nreturn func(*args, **kwds)\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane_orquestra\\orquestra_device.py\u201d, line 504, in batch_execute\nreturn [self.execute(circuits[0], **kwargs)]\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane_orquestra\\orquestra_device.py\u201d, line 429, in execute\nworkflow_id = qe_submit(filepath, keep_file=self._keep_files)\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane_orquestra\\cli_actions.py\u201d, line 73, in qe_submit\nprocess = subprocess.Popen(\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\subprocess.py\u201d, line 951, in init\nself._execute_child(args, executable, preexec_fn, close_fds,\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\subprocess.py\u201d, line 1420, in _execute_child\nhp, ht, pid, tid = _winapi.CreateProcess(executable, args,\nFileNotFoundError: [WinError 2] The system cannot find the file specified", "link": "https://discuss.pennylane.ai//t/file-not-found-errors-when-trying-to-use-pennylane-orquestra/2849/1"}, "1": {"author": "isaacdevlugt", "date": "1681828254983", "content": "Hey @oscar-wallis! Welcome to the forum !\nI\u2019m able to replicate your error with this code:\nimport pennylane as qml\n\ndev_forest = qml.device('orquestra.forest', wires=2)\ndev_qiskit = qml.device('orquestra.qiskit', wires=2)\n\ndevs = [dev_forest, dev_qiskit]\n\ndef circuit():\n    qml.Hadamard(0)\n    qml.Hadamard(1)\n    return qml.expval(qml.PauliZ(0))\n\nfor dev in devs:\n    qnode = qml.QNode(circuit, dev)\n\n    try:\n        print(qnode())\n    except Exception as e:\n        print(e)\n\n'''\n[Errno 2] No such file or directory: 'qe'\n[Errno 2] No such file or directory: 'qe'\n'''\n\nAm speaking with some folks on my side and will get back to you to see if there\u2019s an obvious fix or if it\u2019s a bug !", "link": "https://discuss.pennylane.ai//t/file-not-found-errors-when-trying-to-use-pennylane-orquestra/2849/2"}, "2": {"author": "isaacdevlugt", "date": "1681830237831", "content": "Looks like there\u2019s a bug here! Do you mind making an issue on the plugin\u2019s github?\n\n\n\nGitHub\n\n\n\nBuild software better, together 1\nGitHub is where people build software. More than 100 million people use GitHub to discover, fork, and contribute to over 330 million projects.\n\n\n\n\n\n", "link": "https://discuss.pennylane.ai//t/file-not-found-errors-when-trying-to-use-pennylane-orquestra/2849/3"}, "3": {"author": "oscar-wallis", "date": "1681751381153", "content": "Hi,\nI recently installed the pennylane orquestra plugin as I\u2019m trying to run some hybrid neural nets on IBM hardware but I\u2019m getting file not found errors when trying to use any orquestra backends. I\u2019m running on Python 3.9.13 through Anaconda and have pennylane 0.29.1 and pennylane-orquestra 0.28.0 installed (shown in conda list), and I can run fine on pennylane backends, just having issues on orquestra. I\u2019m not experienced in python environments so I imagine this may not be an orquestra issue but I haven\u2019t had it on any other packages I\u2019ve installed and used thus far. This is the error I\u2019m getting:\nError\nc:\\Users\\oscar\\Documents\\Masters ML\\Neural Net>C:/Users/oscar/anaconda3/python.exe \u201cc:/Users/oscar/Documents/Masters ML/Neural Net/OrquestraTest.py\u201d\nTraceback (most recent call last):\nFile \u201cc:\\Users\\oscar\\Documents\\Masters ML\\Neural Net\\OrquestraTest.py\u201d, line 13, in \nprint(circuit(0,0,1))\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane\\qnode.py\u201d, line 889, in call\nres = qml.execute(\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane\\interfaces\\execution.py\u201d, line 729, in execute\nres = _execute(\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane\\interfaces\\autograd.py\u201d, line 81, in execute\nreturn _execute(\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\autograd\\tracer.py\u201d, line 48, in f_wrapped\nreturn f_raw(*args, **kwargs)\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane\\interfaces\\autograd.py\u201d, line 125, in _execute\nres, jacs = execute_fn(tapes, **gradient_kwargs)\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane\\interfaces\\execution.py\u201d, line 205, in wrapper\nres = fn(execution_tapes.values(), **kwargs)\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane\\interfaces\\execution.py\u201d, line 131, in fn\nreturn original_fn(tapes, **kwargs)\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\contextlib.py\u201d, line 79, in inner\nreturn func(*args, **kwds)\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane_orquestra\\orquestra_device.py\u201d, line 504, in batch_execute\nreturn [self.execute(circuits[0], **kwargs)]\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane_orquestra\\orquestra_device.py\u201d, line 429, in execute\nworkflow_id = qe_submit(filepath, keep_file=self._keep_files)\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\site-packages\\pennylane_orquestra\\cli_actions.py\u201d, line 73, in qe_submit\nprocess = subprocess.Popen(\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\subprocess.py\u201d, line 951, in init\nself._execute_child(args, executable, preexec_fn, close_fds,\nFile \u201cC:\\Users\\oscar\\anaconda3\\lib\\subprocess.py\u201d, line 1420, in _execute_child\nhp, ht, pid, tid = _winapi.CreateProcess(executable, args,\nFileNotFoundError: [WinError 2] The system cannot find the file specified", "link": "https://discuss.pennylane.ai//t/file-not-found-errors-when-trying-to-use-pennylane-orquestra/2849/4"}, "4": {"author": "isaacdevlugt", "date": "1681830237831", "content": "Looks like there\u2019s a bug here! Do you mind making an issue on the plugin\u2019s github?\n\n\n\nGitHub\n\n\n\nBuild software better, together 1\nGitHub is where people build software. More than 100 million people use GitHub to discover, fork, and contribute to over 330 million projects.\n\n\n\n\n\n", "link": "https://discuss.pennylane.ai//t/file-not-found-errors-when-trying-to-use-pennylane-orquestra/2849/5"}}