{"0": {"author": "art", "date": "1661915879172", "content": "I am able to run the Quanvolutional Neural Network example at\n\n\n\npennylane.ai\n\n\n\nQuanvolutional Neural Networks \u2014 PennyLane 5\nTrain a quantum convolutional neural network to classify MNIST images.\n\n\n\n\n\nwith lightning.qubit. However when I switch in lightning.gpu I get the following output:\nQuantum pre-processing of train images:\nTraceback (most recent call last):\nFile \u201cquanvolutional_nn.py\u201d, line 81, in \nq_train_images.append(quanv(img))\nFile \u201cquanvolutional_nn.py\u201d, line 62, in quanv\nq_results = circuit(\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/site-packages/pennylane/qnode.py\u201d, line 660, in call\nres = qml.execute(\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/site-packages/pennylane/interfaces/execution.py\u201d, line 443, in execute\nres = _execute(\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/site-packages/pennylane/interfaces/tensorflow.py\u201d, line 89, in execute\nres, jacs = execute_fn(tapes, **gradient_kwargs)\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/site-packages/pennylane/interfaces/execution.py\u201d, line 197, in wrapper\nres = fn(execution_tapes.values(), **kwargs)\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/site-packages/pennylane/interfaces/execution.py\u201d, line 122, in fn\nreturn original_fn(tapes, **kwargs)\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/contextlib.py\u201d, line 75, in inner\nreturn func(*args, **kwds)\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/site-packages/pennylane/_qubit_device.py\u201d, line 576, in batch_execute\nres = self.execute(circuit)\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/site-packages/pennylane/_qubit_device.py\u201d, line 323, in execute\nresults = self.statistics(circuit.observables)\nFile \u201c/media/arthurlobo/QML/pennylane_lightning_gpu_38/pennylane-lightning-gpu/pennylane_lightning_gpu/lightning_gpu.py\u201d, line 149, in statistics\nreturn super().statistics(observables, shot_range, bin_size, circuit)\nTypeError: statistics() takes from 2 to 4 positional arguments but 5 were given\nAny suggestions?", "link": "https://discuss.pennylane.ai//t/qnn-with-lightning-gpu-device/2120/1"}, "1": {"author": "CatalinaAlbornoz", "date": "1661981040067", "content": "Hi @art, what version of lightning are you using?\nCould you please post de output of qml.about()?\nI can see that we made a change in the statistics (in the dev version) method due to an API change.\nIf you\u2019re using v0.25 you can install the development version by using python -m pip install git+https://github.com/PennyLaneAI/pennylane-lightning-gpu.git#egg=pennylane-lightning-gpu.", "link": "https://discuss.pennylane.ai//t/qnn-with-lightning-gpu-device/2120/2"}, "2": {"author": "art", "date": "1661985652075", "content": "\nCould you please post de output of qml.about() ?\n\n@CatalinaAlbornoz I had been using PennyLane-Lightning-GPU-0.26.0.dev0.\nOutput of qml.about():\nPlatform info:           Linux-5.10.104-tegra-aarch64-with-glibc2.26\nPython version:          3.8.13\nNumpy version:           1.23.2\nScipy version:           1.9.1\nInstalled devices:\n\nlightning.gpu (PennyLane-Lightning-GPU-0.26.0.dev0)\nbraket.aws.qubit (amazon-braket-pennylane-plugin-1.6.9)\nbraket.local.qubit (amazon-braket-pennylane-plugin-1.6.9)\nlightning.qubit (PennyLane-Lightning-0.25.1)\ndefault.gaussian (PennyLane-0.25.1)\ndefault.mixed (PennyLane-0.25.1)\ndefault.qubit (PennyLane-0.25.1)\ndefault.qubit.autograd (PennyLane-0.25.1)\ndefault.qubit.jax (PennyLane-0.25.1)\ndefault.qubit.tf (PennyLane-0.25.1)\ndefault.qubit.torch (PennyLane-0.25.1)\ndefault.qutrit (PennyLane-0.25.1)\n", "link": "https://discuss.pennylane.ai//t/qnn-with-lightning-gpu-device/2120/3"}, "3": {"author": "CatalinaAlbornoz", "date": "1662067414490", "content": "Hi @art,\nI see that you have PennyLane v0.25.1. In that case pennylane-lightning-gpu v0.25.0 should work.\nYou can install it by using python -m pip install pennylane-lightning[gpu]==0.25.0\nDoes this work for you?", "link": "https://discuss.pennylane.ai//t/qnn-with-lightning-gpu-device/2120/4"}, "4": {"author": "art", "date": "1662148589259", "content": "@CatalinaAlbornoz\n\nYou can install it by using python -m pip install pennylane-lightning[gpu]==0.25.0\n\nthe above line did not work for me. qml.about() still shows v0.26.0.dev0.\nFor my aarch64 install @mlxd had suggested the following steps\nwhich builds from source and installs lightning_gpu_qubit_ops.cpython-38-aarch64-linux-gnu.so in the pennylane-lightning-gpu sub-folder:\ngit clone https://github.com/PennyLaneAI/pennylane-lightning-gpu\ncd pennylane-lightning-gpu\npython -m pip install -e .\n\n(installs v0.26.0.dev0).\nIs it possible to checkout a specific branch (0.25.0) to build from source?", "link": "https://discuss.pennylane.ai//t/qnn-with-lightning-gpu-device/2120/5"}, "5": {"author": "mlxd", "date": "1662149405991", "content": "Hi @art\nThe issue here is that for a manual build from lightning.gpu v0.26, you also need the up-to-date master branch of pennylane\nMaybe keep the lightning.gpu (PennyLane-Lightning-GPU-0.26.0.dev0) version, and on-top of it install pennylane as python -m pip install git+https://github.com/PennyLaneAI/pennylane.git@master.\nThat should hopefully fix the issue, until the next release version in a few weeks.1", "link": "https://discuss.pennylane.ai//t/qnn-with-lightning-gpu-device/2120/6"}, "6": {"author": "art", "date": "1662156244676", "content": "@CatalinaAlbornoz that worked. I am able to use lightning.gpu and lightning.qubit with PyTorch and TensorFlow CUDA versions. Note that if I specify default.qubit I get an error as shown:\nPlatform info:           Linux-5.10.104-tegra-aarch64-with-glibc2.26\nPython version:          3.8.13\nNumpy version:           1.23.2\nScipy version:           1.9.1\nInstalled devices:\n\nlightning.gpu (PennyLane-Lightning-GPU-0.26.0.dev0)\nbraket.aws.qubit (amazon-braket-pennylane-plugin-1.6.9)\nbraket.local.qubit (amazon-braket-pennylane-plugin-1.6.9)\ndefault.gaussian (PennyLane-0.26.0.dev0)\ndefault.mixed (PennyLane-0.26.0.dev0)\ndefault.qubit (PennyLane-0.26.0.dev0)\ndefault.qubit.autograd (PennyLane-0.26.0.dev0)\ndefault.qubit.jax (PennyLane-0.26.0.dev0)\ndefault.qubit.tf (PennyLane-0.26.0.dev0)\ndefault.qubit.torch (PennyLane-0.26.0.dev0)\ndefault.qutrit (PennyLane-0.26.0.dev0)\nlightning.qubit (PennyLane-Lightning-0.25.1)\nTraceback (most recent call last):\nFile \u201cquanvolutional_nn.py\u201d, line 39, in \ndev = qml.device(\u201cdefault.qubit\u201d, wires=4)\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/site-packages/pennylane/init.py\u201d, line 314, in device\nraise DeviceError(\npennylane._device.DeviceError: The default.qubit plugin requires PennyLane versions 0.26.0-dev, however PennyLane version 0.26.0-dev is installed.\n", "link": "https://discuss.pennylane.ai//t/qnn-with-lightning-gpu-device/2120/7"}, "7": {"author": "CatalinaAlbornoz", "date": "1662499487270", "content": "Hi @art, thank you for pointing this out. This looks like a bug in our development version. v0.26 should be released in 2 weeks so it should be fixed by then.", "link": "https://discuss.pennylane.ai//t/qnn-with-lightning-gpu-device/2120/8"}, "8": {"author": "art", "date": "1661915879172", "content": "I am able to run the Quanvolutional Neural Network example at\n\n\n\npennylane.ai\n\n\n\nQuanvolutional Neural Networks \u2014 PennyLane 5\nTrain a quantum convolutional neural network to classify MNIST images.\n\n\n\n\n\nwith lightning.qubit. However when I switch in lightning.gpu I get the following output:\nQuantum pre-processing of train images:\nTraceback (most recent call last):\nFile \u201cquanvolutional_nn.py\u201d, line 81, in \nq_train_images.append(quanv(img))\nFile \u201cquanvolutional_nn.py\u201d, line 62, in quanv\nq_results = circuit(\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/site-packages/pennylane/qnode.py\u201d, line 660, in call\nres = qml.execute(\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/site-packages/pennylane/interfaces/execution.py\u201d, line 443, in execute\nres = _execute(\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/site-packages/pennylane/interfaces/tensorflow.py\u201d, line 89, in execute\nres, jacs = execute_fn(tapes, **gradient_kwargs)\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/site-packages/pennylane/interfaces/execution.py\u201d, line 197, in wrapper\nres = fn(execution_tapes.values(), **kwargs)\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/site-packages/pennylane/interfaces/execution.py\u201d, line 122, in fn\nreturn original_fn(tapes, **kwargs)\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/contextlib.py\u201d, line 75, in inner\nreturn func(*args, **kwds)\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/site-packages/pennylane/_qubit_device.py\u201d, line 576, in batch_execute\nres = self.execute(circuit)\nFile \u201c/home/arthurlobo/.conda/envs/qml_py38_b/lib/python3.8/site-packages/pennylane/_qubit_device.py\u201d, line 323, in execute\nresults = self.statistics(circuit.observables)\nFile \u201c/media/arthurlobo/QML/pennylane_lightning_gpu_38/pennylane-lightning-gpu/pennylane_lightning_gpu/lightning_gpu.py\u201d, line 149, in statistics\nreturn super().statistics(observables, shot_range, bin_size, circuit)\nTypeError: statistics() takes from 2 to 4 positional arguments but 5 were given\nAny suggestions?", "link": "https://discuss.pennylane.ai//t/qnn-with-lightning-gpu-device/2120/9"}}