{"0": {"author": "Maham_Iftikhar", "date": "1676403381147", "content": "Hi\u2026i am trying to modify the quanvolutional neural network demo in which they have used MINST Dataset for classification but i am trying to use MIT BIH Dataset for ecg classification using quanvolutional neural networks. i have already preprocessed the ecg dataset by converting the 1D ecg signal to 2D ECG images in .csv file. but using this data i have encountered some error kindly help me to understand the error and give me the best possible solution. its for my thesis work. Thanks\nif PREPROCESS == True:\n    q_train_images = []\n    print(\"Quantum pre-processing of train images:\")\n    for idx, img in enumerate(train_images):\n        print(\"{}/{}        \".format(idx + 1, n_train), end=\"\\r\")\n        q_train_images.append(quanv(img))\n    q_train_images = np.asarray(q_train_images)\n\n    q_test_images = []\n    print(\"\\nQuantum pre-processing of test images:\")\n    for idx, img in enumerate(test_images):\n        print(\"{}/{}        \".format(idx + 1, n_test), end=\"\\r\")\n        q_test_images.append(quanv(img))\n    q_test_images = np.asarray(q_test_images)\n\n    # Save pre-processed images\n    np.save(SAVE_PATH + \"q_train_images.npy\", q_train_images)\n    np.save(SAVE_PATH + \"q_test_images.npy\", q_test_images)\n\n    # Load pre-processed images\nq_train_images = np.load(SAVE_PATH + \"q_train_images.npy\")\nq_test_images = np.load(SAVE_PATH + \"q_test_images.npy\")\n\nbelow is the error\n---------------------------------------------------------------------------\nValueError                                Traceback (most recent call last)\n<ipython-input-46-047b3a4e5f4c> in <module>\n      4     for idx, img in enumerate(train_images):\n      5         print(\"{}/{}        \".format(idx + 1, n_train), end=\"\\r\")\n----> 6         q_train_images.append(quanv(img))\n      7     q_train_images = np.asarray(q_train_images)\n      8 \n\n8 frames\n/usr/local/lib/python3.8/dist-packages/pennylane/operation.py in _check_batching(self, params)\n    926             ]\n    927             if not all(correct or batched for correct, batched in ndims_matches):\n--> 928                 raise ValueError(\n    929                     f\"{self.name}: wrong number(s) of dimensions in parameters. \"\n    930                     f\"Parameters with ndims {ndims} passed, {self.ndim_params} expected.\"\n\n**ValueError: RY: wrong number(s) of dimensions in parameters. Parameters with ndims (2,) passed, (0,) expected**.\ntype or paste code here\n", "link": "https://discuss.pennylane.ai//t/error-when-using-ecg-dataset-on-quanvolutional-neural-nework-demo-valueerror-ry-wrong-number-s-of-dimensions-in-parameters-parameters-with-ndims-2-passed-0-expected/2553/1"}, "1": {"author": "Alvaro_Ballon", "date": "1676495025319", "content": "Hello @Maham_Iftikhar Welcome to the Forum!\nIt seems that the image processing might be an issue here. We might be able to help you more if we knew what train_images looks like, or how it was produced.\nCheers,\nAlvaro", "link": "https://discuss.pennylane.ai//t/error-when-using-ecg-dataset-on-quanvolutional-neural-nework-demo-valueerror-ry-wrong-number-s-of-dimensions-in-parameters-parameters-with-ndims-2-passed-0-expected/2553/2"}, "2": {"author": "Maham_Iftikhar", "date": "1676556875199", "content": "@Alvaro_Ballon i am sharing the github link with you. i have used the same approach as given in this link. ECG_Classification_with_2D_CNN/ECG_Heartbeat_Classification_2Dconv.02b.etl-Copy1.ipynb at main \u00b7 celiedel/ECG_Classification_with_2D_CNN \u00b7 GitHub 4\nit will help you to understand it easily.", "link": "https://discuss.pennylane.ai//t/error-when-using-ecg-dataset-on-quanvolutional-neural-nework-demo-valueerror-ry-wrong-number-s-of-dimensions-in-parameters-parameters-with-ndims-2-passed-0-expected/2553/3"}, "3": {"author": "CatalinaAlbornoz", "date": "1677197653063", "content": "Hi @Maham_Iftikhar, Thank you for sharing the code. Could you please send us a minimal example that replicates your error? Maybe try with a code that uses only a single image. I believe that the error is that your image has 2 dimensions and PennyLane thinks you\u2019re sending a batch. You probably need to turn that 2D data into 1D and then train based on this.\nPlease let me know if this helps and if you can send us a small but self-contained example of your issue we can help you better.", "link": "https://discuss.pennylane.ai//t/error-when-using-ecg-dataset-on-quanvolutional-neural-nework-demo-valueerror-ry-wrong-number-s-of-dimensions-in-parameters-parameters-with-ndims-2-passed-0-expected/2553/4"}, "4": {"author": "Maham_Iftikhar", "date": "1677928403538", "content": "Thanks @CatalinaAlbornoz for your suggestion. Error is solved now, actually it was due to the invalid shape of training images which in my case was not 28x28 pixels as used in the pennylane code using MINST dataset. By reshaping the train images my error eliminates and the code works properly.", "link": "https://discuss.pennylane.ai//t/error-when-using-ecg-dataset-on-quanvolutional-neural-nework-demo-valueerror-ry-wrong-number-s-of-dimensions-in-parameters-parameters-with-ndims-2-passed-0-expected/2553/5"}, "5": {"author": "CatalinaAlbornoz", "date": "1678209740694", "content": "I\u2019m glad you could find the solution @Maham_Iftikhar ! And thank you for sharing it here ", "link": "https://discuss.pennylane.ai//t/error-when-using-ecg-dataset-on-quanvolutional-neural-nework-demo-valueerror-ry-wrong-number-s-of-dimensions-in-parameters-parameters-with-ndims-2-passed-0-expected/2553/6"}, "6": {"author": "Maham_Iftikhar", "date": "1676403381147", "content": "Hi\u2026i am trying to modify the quanvolutional neural network demo in which they have used MINST Dataset for classification but i am trying to use MIT BIH Dataset for ecg classification using quanvolutional neural networks. i have already preprocessed the ecg dataset by converting the 1D ecg signal to 2D ECG images in .csv file. but using this data i have encountered some error kindly help me to understand the error and give me the best possible solution. its for my thesis work. Thanks\nif PREPROCESS == True:\n    q_train_images = []\n    print(\"Quantum pre-processing of train images:\")\n    for idx, img in enumerate(train_images):\n        print(\"{}/{}        \".format(idx + 1, n_train), end=\"\\r\")\n        q_train_images.append(quanv(img))\n    q_train_images = np.asarray(q_train_images)\n\n    q_test_images = []\n    print(\"\\nQuantum pre-processing of test images:\")\n    for idx, img in enumerate(test_images):\n        print(\"{}/{}        \".format(idx + 1, n_test), end=\"\\r\")\n        q_test_images.append(quanv(img))\n    q_test_images = np.asarray(q_test_images)\n\n    # Save pre-processed images\n    np.save(SAVE_PATH + \"q_train_images.npy\", q_train_images)\n    np.save(SAVE_PATH + \"q_test_images.npy\", q_test_images)\n\n    # Load pre-processed images\nq_train_images = np.load(SAVE_PATH + \"q_train_images.npy\")\nq_test_images = np.load(SAVE_PATH + \"q_test_images.npy\")\n\nbelow is the error\n---------------------------------------------------------------------------\nValueError                                Traceback (most recent call last)\n<ipython-input-46-047b3a4e5f4c> in <module>\n      4     for idx, img in enumerate(train_images):\n      5         print(\"{}/{}        \".format(idx + 1, n_train), end=\"\\r\")\n----> 6         q_train_images.append(quanv(img))\n      7     q_train_images = np.asarray(q_train_images)\n      8 \n\n8 frames\n/usr/local/lib/python3.8/dist-packages/pennylane/operation.py in _check_batching(self, params)\n    926             ]\n    927             if not all(correct or batched for correct, batched in ndims_matches):\n--> 928                 raise ValueError(\n    929                     f\"{self.name}: wrong number(s) of dimensions in parameters. \"\n    930                     f\"Parameters with ndims {ndims} passed, {self.ndim_params} expected.\"\n\n**ValueError: RY: wrong number(s) of dimensions in parameters. Parameters with ndims (2,) passed, (0,) expected**.\ntype or paste code here\n", "link": "https://discuss.pennylane.ai//t/error-when-using-ecg-dataset-on-quanvolutional-neural-nework-demo-valueerror-ry-wrong-number-s-of-dimensions-in-parameters-parameters-with-ndims-2-passed-0-expected/2553/7"}}